@startuml

!include kargu_sequence.iuml

title <b>Kargu</b> | Diagram Urutan\nMengurutkan Entri\n

participant KarguDesktopGUI as KDG
participant Controller as C
participant Document as D
participant Entry as E

KDG -> C : doSortEntry()
KDG <- C : getDocument()
KDG --> C

C -> E : sortEntry()
D -> D : setChanged()

@enduml

