@startuml

!include kargu_activity.iuml

title <b>Kargu</b> | Diagram Aktivitas\nMemberhentikan Aplikasi\n

start

:Memilih menu "Berkas";
:Memilih menu "Berhenti";

if (Ada dokumen aktif?) then (Ya)
  :<Mengecek kondisi perubahan>;
else (Tidak)
endif

:Menutup dokumen;
:Memberhentikan aplikasi\ndan membunuh proses;

stop

@enduml
